import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# !!!!! IMPORTANT !!!!!
# Define pathvars for all user resource files and result files
# This allows users to re-wire how the module is used in their workflow with ease.
pathvars:
    # User resources
    shapes="<resources>/user/shapes/{shape}.parquet",
    wdpa="<resources>/user/wdpa.gdb",
    # Module results
    area_potential="<results>/{shape}/area_potential_{tech}.tif",


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)

# Python files that are imported from other scripts and need to be included when accessing the module
workflow.source_path("scripts/_geo.py")
workflow.source_path("scripts/_schemas.py")
workflow.source_path("scripts/_script_utils.py")


wildcard_constraints:
    shape="[a-zA-Z0-9_-]+",
    subunit="[a-zA-Z0-9_]+",
    tech="|".join(config["techs"].keys()),


# Add all your includes here.
include: "rules/functions.smk"
include: "rules/automatic.smk"
include: "rules/process.smk"


rule all:
    default_target: True
    output:
        "INVALID",
    log:
        stderr="<logs>/all.stderr",
    conda:
        "envs/module.yaml"
    message:
        "ERROR: Invalid `rule all:` call"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
