# Changes here will be overwritten by Copier
# !!!!! DO NOT MANUALLY MODIFY THIS FILE !!!!!
_commit: v1.0.3
_src_path: https://github.com/modelblocks-org/data-module-template
authors:
-   email: L.Ho@tudelft.nl
    family_name: Ho-Tran
    given_name: Linh
-   email: s.pfenninger@tudelft.nl
    family_name: Pfenninger-Lee
    given_name: Stefan
github_org: modelblocks-org
license: Apache-2.0
maintainers:
-   email: s.pfenninger@tudelft.nl
    family_name: Pfenninger-Lee
    given_name: Stefan
module_code_name: module_area_potentials
module_description: This module performs geospatial analyses to determine the available
    land area for specific technologies, on a by-pixel basis and aggregated to given
    geographic boundaries.
module_human_name: Area potentials
