# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


rule download_netherlands_shapes:
    message:
        "Download and unzip the Netherlands shapes."
    output:
        "results/integration_test/resources/user/shapes/NLD.parquet",
    log:
        "results/integration_test/logs/download_netherlands_shapes.log",
    conda:
        "../../workflow/envs/shell.yaml"
    shell:
        """
        curl -sSLo "{output}" "https://surfdrive.surf.nl/files/index.php/s/ey3RmiCbajp69oQ/download"
        """


rule download_netherlands_protected_areas:
    message:
        "Download and unzip a dummy drop-in dataset for Netherlands protected areas (not based on WDPA)."
    output:
        "results/integration_test/resources/user/wdpa.gdb.zip"
    log:
        "results/integration_test/logs/download_netherlands_protected_areas.log",
    conda:
        "../../workflow/envs/shell.yaml"
    shell:
        """
        curl -sSLo "{output}" "https://surfdrive.surf.nl/files/index.php/s/msuXQETNbCWawDh/download"
        """

rule unzip_netherlands_protected_areas:
    message:
        "Download and unzip a dummy drop-in dataset for Netherlands protected areas (not based on WDPA)."
    input:
        script=workflow.source_path("../../workflow/scripts/unzip_like.py"),
        zipfile=rules.download_netherlands_protected_areas.output,
    output:
        directory("results/integration_test/resources/user/wdpa.gdb"),
    log:
        "results/integration_test/logs/unzip_netherlands_protected_areas.log",
    conda:
        "../../workflow/envs/shell.yaml"
    shell:
        """
        python "{input.script}" "{input.zipfile}" -t "results/integration_test/resources/user/" 2> "{log}"
        """


# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `prefix:` re-routes all input/output paths of the module, helping to avoid file conflicts.
module module_area_potentials:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_area_potentials"]
    prefix:
        "results/integration_test/"


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_area_potentials as module_area_potentials_*


# Request something from the module
rule all:
    message:
        "Run the module for the Netherlands shapes."
    default_target: True
    input:
        "results/integration_test/resources/user/shapes/NLD.parquet",
        "results/integration_test/resources/user/wdpa.gdb",
        "results/integration_test/results/NLD/area_potential_report.html",
