$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  techs:
    type: object
    additionalProperties:
      type: object
      additionalProperties: false
      properties:
        max_slope:
          type: number
      required: [max_slope]
required: [techs]
