$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  specs:
    type: object
    properties:
      projection:
        type: string
      resolution:
        type: number
    required: [projection, resolution]
    additionalProperties: false

  techs_onshore:
    type: object
    additionalProperties:
      type: object
      properties:
        max_slope:
          type: number
        land_cover:
          type: object
          additionalProperties:
            type: number
        settlement:
          type: object
          properties:
            max_settlement:
              type: number
            weight:
              type: number
          required: [max_settlement, weight]
          additionalProperties: false
      required: [max_slope, land_cover, settlement]
      additionalProperties: false

  techs_offshore:
    type: object
    additionalProperties:
      type: object
      properties:
        water_depth:
          type: object
          additionalProperties:
            type: number
        weight:
          type: number
      required: [water_depth, weight]
      additionalProperties: false

required: [techs_onshore, techs_offshore]
