# Module settings that users cannot modify.
resources:
  automatic:
    ##
    # Links for automatically downloaded files
    ##
    # Slope
    slope_gmted2010_opendap: "https://opendap.4tu.nl/thredds/dodsC/data2/test/slope-global_20101117_gmted_mea075.nc"
    slope_gmted2010: "https://surfdrive.surf.nl/files/index.php/s/S4dFpFW9aJDPcVr/download"
    # Land cover
    globcover: "https://due.esrin.esa.int/files/Globcover2009_V2.3_Global_.zip"
    globcover_landcover_tif: "GLOBCOVER_L4_200901_200912_V2.3.tif"
    globcover_landseamask_tif: "GLOBCOVER_L4_200901_200912_V2.3_CLA_QL.tif"
    # Bathymetry
    gebco: "https://www.bodc.ac.uk/data/open_download/gebco/gebco_2024_sub_ice_topo/geotiff/"
    gebco_tif: "gebco_2024_sub_ice_topo.tif"
    # Built-up areas
    ghsl: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_BUILT_S_GLOBE_R2023A/GHS_BUILT_S_E2025_GLOBE_R2023A_54009_100/V1-0/GHS_BUILT_S_E2025_GLOBE_R2023A_54009_100_V1_0.zip"
    ghsl_tif: "GHS_BUILT_S_E2025_GLOBE_R2023A_54009_100_V1_0.tif"
    # Protected areas
    wdpa: "https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_Jun2025_Public.zip"
    wdpa_gdb: "WDPA_Jun2025_Public.gdb"
