# Module settings that users cannot modify.
resources:
  automatic:
    ##
    # Links for automatically downloaded files
    ##
    slope: "https://zenodo.org/records/14920379/files/slope.in.degree_edtm_m_240m_s_20000101_20221231_go_epsg.4326_v20241230.tif"
    bathymetry: "https://zenodo.org/records/15741950/files/gebco_2024_sub_ice_cog.tif"
    globcover: "https://due.esrin.esa.int/files/Globcover2009_V2.3_Global_.zip"
    globcover_landcover_tif: "GLOBCOVER_L4_200901_200912_V2.3.tif"
    ghsl: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_BUILT_S_GLOBE_R2023A/GHS_BUILT_S_E2025_GLOBE_R2023A_4326_30ss/V1-0/GHS_BUILT_S_E2025_GLOBE_R2023A_4326_30ss_V1_0.zip"
    ghsl_tif: "GHS_BUILT_S_E2025_GLOBE_R2023A_4326_30ss_V1_0.tif"

land_cover_types:
  POST_FLOODING: FARM
  RAINFED_CROPLANDS: FARM
  MOSAIC_CROPLAND: FARM
  MOSAIC_VEGETATION: FARM
  CLOSED_TO_OPEN_BROADLEAVED_FOREST: FOREST
  CLOSED_BROADLEAVED_FOREST: FOREST
  OPEN_BROADLEAVED_FOREST: FOREST
  CLOSED_NEEDLELEAVED_FOREST: FOREST
  OPEN_NEEDLELEAVED_FOREST: FOREST
  CLOSED_TO_OPEN_MIXED_FOREST: FOREST
  MOSAIC_FOREST: FOREST
  CLOSED_TO_OPEN_REGULARLY_FLOODED_FOREST: FOREST
  CLOSED_REGULARLY_FLOODED_FOREST: FOREST
  MOSAIC_GRASSLAND: OTHER
  CLOSED_TO_OPEN_SHRUBLAND: OTHER
  CLOSED_TO_OPEN_HERBS: OTHER
  SPARSE_VEGETATION: OTHER
  CLOSED_TO_OPEN_REGULARLY_FLOODED_GRASSLAND: OTHER
  BARE_AREAS: OTHER
  ARTIFICIAL_SURFACES_AND_URBAN_AREAS: URBAN
  WATER_BODIES: WATER
  PERMANENT_SNOW: NOT_SUITABLE
  NO_DATA: NOT_SUITABLE
