# Options for buffering: either a string of the form "epsg:xxxx" or "UTM"/"utm"
# - "UTM": project each shape to the UTM zone of its centroid for buffering
# - "epsg:xxxx": use the specified CRS for all buffering
#   A good option is "epsg:8857" (WGS 84 / Equal Earth Greenwich) for global coverage
buffer_crs: "epsg:8857"

# Technical criteria
techs_onshore:
  pv_open_field:
    max_slope: 3
    land_cover:
      FARM: 0.1
      FOREST: 0  # no PV open field in forest
      OTHER: 0.2
      URBAN: 0  # no PV open field in urban
    settlement:
      max_settlement: 0.01 # no PV open field in settlement
      weight: -1
  wind_onshore:
    max_slope: 20
    land_cover:
      FARM: 0.2
      FOREST: 0.05
      OTHER: 0.3
      URBAN: 0  # no wind onshore in urban
    settlement:
      max_settlement: 0.01
      weight: -1
  pv_rooftop:
    max_slope: 90
    land_cover:
      FARM: 0
      FOREST: 0
      OTHER: 0
      URBAN: 1
    settlement:
      max_settlement: 1
      weight: 0.8

techs_offshore:
  wind_offshore:
    water_depth:
      max: 0
      min: -50
    weight: 0.8
